### ISSUE TITLE
Can't update cfg file org.apache.karaf.command.acl.bundle.cfg

### ISSUE THREAD

**Issue by bqluan** [sonatype/docker-nexus3#30]
Hi there,

I saw the following log when starting the container. Should this (**Can't update cfg file**) be fixed?

[Cause] The org.apache.karaf.command.acl.bundle.cfg file belongs to the **root** user, the java process runs as **nexus** user and doesn't have permission to modify it.

======= LOG ======
2016-09-26 08:22:42,575+0000 WARN  [pool-15-thread-1]  org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/org.apache.karaf.command.acl.bundle.cfg (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) [na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) [na:1.8.0_102]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:152) [org.apache.karaf.features.core:4.0.4]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:148) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:292) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:107) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:1166) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:778) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1089) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:985) [org.apache.karaf.features.core:4.0.4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

**Comment by joedragons** [comment]
I am pretty sure this is https://issues.sonatype.org/browse/NEXUS-10049 which is slated to be fixed already.  Feel free to watch/vote for that issue there.  If I am misunderstanding and this is distinct, please feel free to comment here.
