### ISSUE TITLE
File Permissions issues?

### ISSUE THREAD

**Issue by rcarmich** [sonatype/docker-nexus3#38]
I'm trying to run this on my Max (El Capitan 10.11.6) and the logs produce a lot of errors when starting up. The "ping" test works, but trying to go navigate to 8081 in a browser redirects me to /artifactory with a warning "404 not found".

```

docker run -d -p 8081:8081 --name nexus sonatype/nexus3 && docker logs -f nexus

77057683d6d9852cd9ff082f90224c1214a810ad9955ce616d5aab517e249c3a
2016-10-12 14:00:41,217+0000 WARN  [pool-15-thread-1]  org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/org.apache.karaf.command.acl.feature.cfg (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) [na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) [na:1.8.0_102]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:152) [org.apache.karaf.features.core:4.0.4]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:148) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:292) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:107) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:1166) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:778) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1089) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:985) [org.apache.karaf.features.core:4.0.4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-10-12 14:00:41,221+0000 WARN  [pool-15-thread-1]  org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/org.apache.karaf.command.acl.bundle.cfg (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) [na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) [na:1.8.0_102]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:152) [org.apache.karaf.features.core:4.0.4]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:148) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:292) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:107) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:1166) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:778) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1089) [org.apache.karaf.features.core:4.0.4]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:985) [org.apache.karaf.features.core:4.0.4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-10-12 14:00:41,223+0000 WARN  [pool-15-thread-1]  org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/org.apache.karaf.command.acl.system.cfg (Permission denied)

```

There are many more errors but they're all similar to those. In the end it does say "Started Sonatype Nexus OSS 3.0.2-02", but when just navigate to http://IP:8081 the logs say:

```
2016-10-12 14:02:34,207+0000 INFO  [qtp313582153-79] *UNKNOWN org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Enabling session validation scheduler...
2016-10-12 14:02:34,215+0000 INFO  [qtp313582153-79] *UNKNOWN org.sonatype.nexus.security.internal.AnonymousManagerImpl - Using default configuration: AnonymousConfiguration{enabled=true, userId='anonymous', realmName='NexusAuthorizingRealm'}
```

It never asks me for a login.

**Comment by DarthHater** [comment]
It seems very odd that your browser would redirect to /artifactory? Are you sure you don't have something else locally causing that to happen?

**Comment by rcarmich** [comment]
Huh, I must have had some weirdness going on. I deleted my /var/lib/docker and started over and now it's working. Sorry for false alarm - probably was some kind of browser cache issue.
