### ISSUE TITLE
Cannot install google-protobuf gem on Mac OS X

### ISSUE THREAD

**Issue by sullerandras** [sonatype/docker-nexus3#52]
I'm working on a project with lots of gems, so to speed up bundle installs i wanted to use a local rubygems proxy. It worked for many gems but `google-protobuf` throws error during bundle install:
```
Gem::RemoteFetcher::FetchError: bad response Server Error 500 (http://localhost:8081/repository/rubygems-proxy/gems/google-protobuf-3.1.0-universal-darwin.gem)
An error occurred while installing google-protobuf (3.1.0), and Bundler cannot continue.
Make sure that `gem install google-protobuf -v '3.1.0'` succeeds before bundling.
```

The error in the server logs (using `docker logs`):
```
2016-11-07 06:00:13,462+0000 WARN  [qtp177685821-100] *UNKNOWN org.sonatype.nexus.repository.httpbridge.internal.ViewServlet - Service failure
java.lang.IllegalArgumentException: platform string needs none or two '-': universal-darwin
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) [na:1.8.0_102]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [na:na]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [na:na]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46) [na:na]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91) [na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [na:na]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [na:na]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [na:na]
	at org.sonatype.nexus.repository.rubygems.marshal.GemPlatform.<init>(GemPlatform.groovy:47) [na:na]
```

Steps to reproduce:
```
➜  ~$ docker volume create --name nexus-data
nexus-data
➜  ~$ docker run -d -p 8081:8081 --name nexus -v nexus-data:/nexus-data sonatype/docker-nexus3
395247bbeda46c2e2c81b45ea5be776110cb1172963ee217eaf88cc7a6e15974
# now log in to the admin interface and create a repository named "rubygems-proxy" to mirror "https://rubygems.org"
➜  ~$ bundle config mirror.https://rubygems.org http://localhost:8081/repository/rubygems-proxy/
➜  ~$ cd tmp/
➜  tmp$ mkdir test-nexus3
➜  tmp$ cd test-nexus3
➜  test-nexus3$ cat > Gemfile
source 'https://rubygems.org'
gem 'google-protobuf'
➜  test-nexus3$ cat > .ruby-version
2.3.1
➜  test-nexus3$ cat > .ruby-gemset
test-nexus3
➜  test-nexus3$ cd
➜  ~$ cd -
~/tmp/test-nexus3
ruby-2.3.1 - #gemset created /Users/andrassuller/.rvm/gems/ruby-2.3.1@test-nexus3
ruby-2.3.1 - #generating test-nexus3 wrappers - please wait
➜  test-nexus3$ gem install bundler
Fetching: bundler-1.13.6.gem (100%)
Successfully installed bundler-1.13.6
1 gem installed
➜  test-nexus3$ bundle install
Fetching gem metadata from http://localhost:8081/repository/rubygems-proxy/..
Fetching version metadata from http://localhost:8081/repository/rubygems-proxy/.
Resolving dependencies...
Using bundler 1.13.6
Gem::RemoteFetcher::FetchError: bad response Server Error 500 (http://localhost:8081/repository/rubygems-proxy/gems/google-protobuf-3.1.0-universal-darwin.gem)
An error occurred while installing google-protobuf (3.1.0), and Bundler cannot continue.
Make sure that `gem install google-protobuf -v '3.1.0'` succeeds before bundling.
➜  test-nexus3$
```

**Comment by DarthHater** [comment]
Hi there,

This is likely an issue with Nexus and not the Docker image. Mind popping over to: https://issues.sonatype.org/browse/NEXUS and reporting there?

**Comment by kellyrob99** [comment]
This sounds like https://issues.sonatype.org/browse/NEXUS-10970 which should be fixed in 3.1.0

**Comment by joedragons** [comment]
I attempted this without docker on the latest NXRM3 and encountered similar issues however once I upgraded ruby and bundler (both behind what you were using), I no longer had them.  So I hope using the latest NXRM helps.

**Comment by sullerandras** [comment]
Yes, it seems like my docker image was old, it was 3.0.2.
After `docker pull sonatype/docker-nexus3` i got the 3.1.0 version, which works.
Thanks guys. I'm closing this.
