### ISSUE TITLE
java.io.FileNotFoundException: [...]/org.apache.karaf.command.acl.feature.cfg

### ISSUE THREAD

**Issue by Rotwang** [sonatype/docker-nexus3#53]
Hi,

I'm encountering following issue when running "clean" nexus 3.1 from your image:
```
2016-11-09 16:38:04,603+0000 WARN  [pool-16-thread-1] *SYSTEM org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/karaf/org.apache.karaf.command.acl.feature.cfg (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) [na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) [na:1.8.0_102]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:153) [org.apache.karaf.features.core:4.0.5]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:149) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:305) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:115) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:1229) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:778) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1152) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1048) [org.apache.karaf.features.core:4.0.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-11-09 16:38:04,698+0000 WARN  [pool-16-thread-1] *SYSTEM org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/karaf/org.apache.karaf.command.acl.system.cfg (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) [na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) [na:1.8.0_102]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:153) [org.apache.karaf.features.core:4.0.5]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:149) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:305) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:115) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:1229) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:778) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1152) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1048) [org.apache.karaf.features.core:4.0.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-11-09 16:38:04,783+0000 WARN  [pool-16-thread-1] *SYSTEM org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/karaf/org.apache.karaf.command.acl.bundle.cfg (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) [na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) [na:1.8.0_102]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:153) [org.apache.karaf.features.core:4.0.5]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:149) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:305) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:115) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:1229) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:778) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1152) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1048) [org.apache.karaf.features.core:4.0.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-11-09 16:38:04,868+0000 WARN  [pool-16-thread-1] *SYSTEM org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/karaf/org.apache.karaf.command.acl.shell.cfg (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) [na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) [na:1.8.0_102]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:153) [org.apache.karaf.features.core:4.0.5]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:149) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:305) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:115) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:1229) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:773) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1152) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1048) [org.apache.karaf.features.core:4.0.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-11-09 16:38:04,953+0000 WARN  [pool-16-thread-1] *SYSTEM org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/karaf/org.apache.karaf.command.acl.config.cfg (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) [na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) [na:1.8.0_102]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:153) [org.apache.karaf.features.core:4.0.5]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:149) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:305) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:115) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:1229) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:778) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1152) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1048) [org.apache.karaf.features.core:4.0.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-11-09 16:38:05,042+0000 WARN  [pool-16-thread-1] *SYSTEM org.apache.karaf.features.internal.service.FeaturesServiceImpl - Can't update cfg file
java.io.FileNotFoundException: /opt/sonatype/nexus/etc/karaf/org.apache.karaf.command.acl.jaas.cfg (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) [na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) [na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) [na:1.8.0_102]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:153) [org.apache.karaf.features.core:4.0.5]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:149) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:305) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:115) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:1229) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:778) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1152) [org.apache.karaf.features.core:4.0.5]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1048) [org.apache.karaf.features.core:4.0.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
```

**Comment by joedragons** [comment]
@Rotwang This appears to be https://issues.sonatype.org/browse/NEXUS-10049.  Are you able to start Nexus Repository Manager a second time without error?  Is this causing bad behavior in any way?  Or are you just reporting the WARN?  Thanks.

**Comment by Rotwang** [comment]
Nexus run without issues (or so it seems) despite of this warning. After a restart the problem doesn't go away.

**Comment by joedragons** [comment]
Thanks, I've made an internal note.

**Comment by mcculls** [comment]
These exceptions don't affect functionality and can be ignored - they come from the Karaf container which tries to create some optional ACL placeholder files (they ship as part of its features which are installed on boot) but it can't create them because the directory is read-only.

These files aren't actually needed by Nexus because we configure Karaf to use Shiro as a backend, but it still tries to create them even though they'll never be used. They should be gone in the next release.

**Comment by joedragons** [comment]
Going to close out and track progress via the JIRA.

**Comment by frekele** [comment]
Temporary Fix for issue https://issues.sonatype.org/browse/NEXUS-10049
> RUN touch ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.feature.cfg \
>   && touch ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.system.cfg \
>   && touch ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.bundle.cfg \
>   && touch ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.shell.cfg \
>   && touch ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.config.cfg \
>   && touch ${NEXUS_HOME}/etc/karaf/org.apache.karaf.command.acl.jaas.cfg
